"""Generate gallery-data.js from assets/gallery; --watch detects additions/removals."""
import argparse
import json
from pathlib import Path
import time
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
EXTENSIONS = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'}

def build():
    folder = ROOT / 'assets/gallery'
    images = [quote(p.relative_to(ROOT).as_posix(), safe='/') for p in sorted(folder.iterdir(), key=lambda p: p.name.casefold()) if p.is_file() and p.suffix.lower() in EXTENSIONS]
    content = '// Generated by scripts/build-gallery.py.\nwindow.FARAZI_GALLERY = ' + json.dumps(images, ensure_ascii=False, indent=2) + ';\n'
    output = ROOT / 'gallery-data.js'
    if not output.exists() or output.read_text(encoding='utf-8') != content:
        output.write_text(content, encoding='utf-8')
        print(f'Gallery updated: {len(images)} images', flush=True)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--watch', action='store_true')
    args = parser.parse_args()
    build()
    if args.watch:
        try:
            while True:
                time.sleep(1)
                build()
        except KeyboardInterrupt:
            pass
